name: Aws tools test

run-name: ${{ inputs.env_name }} operation

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "env name; eg: sandbox"
        default: sandbox
        required: true
        type: choice
        options:
          - sandbox
          - dev
          - staging
          - prod

jobs:
  setup-aws-tools:
    name: Setup aws-tools
    uses: ./.github/workflows/setup-aws-tools.yaml
    with:
      version: 0.0.3

  clear-iam-cert:
    name: clear iam cert
    needs: setup-aws-tools
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: Pwd
        run: pwd
      - name: download and clear
        run: ./linux-amd64-aws-tools iam delete-expired-certification
        env:
          ENV_NAME: ${{ env.ENV_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: cn-northwest-1
