name: action catch test

run-name: "action: ${{ inputs.action }}"

on:
  workflow_dispatch:
    inputs:
      action:
        type: string
        description: operation what?

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - uses: actions/cache@v3
        id: cache-node-module
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          path: node_modules

      - name: Install Depedency
        if: steps.cache-node-module.outputs.cache-hit != 'true'
        run: yarn install

      - uses: actions/cache@v3
        id: aws-tools
        with:
          key: aws-tools-${{ hashFiles('linux-amd64-aws-tools') }}
          path: linux-amd64-aws-tools

      - name: download aws-tools
        run: |
          if [ ! -f linux-amd64-aws-tools ]; then
            wget -q https://github.com/nnsay/aws-tools/releases/download/v0.0.3/linux-amd64-aws-tools
            chmod +x linux-amd64-aws-tools
          fi
