name: Custom commit check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      is-upgrade-commit: ${{ steps.check-commit.outputs.is-upgrade-commit }}
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check upgrade commit
        id: check-commit
        if: contains(github.event.head_commit.message, 'upgrade version')
        run: |
          echo 1
          echo ${{ github.action }}
          echo 2
          isUpgradeCommit=${{ contains(github.event.head_commit.message, 'upgrade version') }}
          echo 3
          echo "is-upgrade-commit=$isUpgradeCommit" >> $GITHUB_OUTPUT
          echo 4
