name: Custom commit check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      is-upgrade-commit: ${{ steps.check-commit.outputs.is-upgrade-commit }}
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check upgrade commit
        id: check-commit
        if: contains(github.event.head_commit.message, 'upgrade version')
        run: |
          echo ${{ github.action_ref }}
          echo ${{ github.action }}
          echo ${{ toJSON(github) }}
          is-upgrade-commit=${{ contains(github.event.head_commit.message, 'upgrade version') }}
          echo "is-upgrade-commit=$is-upgrade-commit" >> $GITHUB_OUTPUT
  useage:
    runs-on: ubuntu-latest
    name: Use the checked commit
    needs: check
    steps:
      - name: Output the checked commit
        run: |
          echo ${{ needs.check.outputs.is-upgrade-commmit }}
