name: Custom commit check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      is-upgrade-commit: ${{ steps.check-commit.outputs.is-upgrade-commit }}
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check upgrade commit
        id: check-commit
        run: |
          echo ${{ github.action_ref }}
          echo ${{ github.action }}
          is-upgrade-commit=$(git show -s --format=%B | grep 'upgrade version')
          if [ $is-upgrade-commit ]; then
            echo "is-upgrade-commit=$is-upgrade-commit" >> $GITHUB_OUTPUT
          fi
  useage:
    runs-on: ubuntu-latest
    name: Use the checked commit
    needs: check
    steps:
      - name: Output the checked commit
        run: |
          echo ${{ needs.check.outputs.is-upgrade-commmit }}
