name: Custom commit check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest commit
    steps:
      - name: Check upgrade commit
        run: |
          echo ${{ github.action_ref }}
          echo ${{ github.action }}
          echo ${{ event.action }}
          echo ${{ event.sha }}

