name: env parameters test

run-name: ${{ inputs.env_name }} operation 

on:
  workflow_dispatch:

env:
  JOB_ENV1: p1
  JOB_ENV2: p2

jobs:
  test:
    name: check environments
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: check env
        run: |
          env
        env:
          STEP_ENV1: 1
          STEP_ENV2: 2

