name: Git replace

on: workflow_dispatch

jobs:
  git:
    name: replace git
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: test
        run: |
          export OLDPATH=$PATH
          export PATH="$(pwd)/bin:$PATH"
          echo PATH $PATH
          which git
          touch demo.log
          git add demo.log
          git status
