name: Git submodule

on: workflow_dispatch

jobs:
  submodule:
    name: submodule
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Apply the node_modules cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('package.json') }}
          path: node_modules

      - name: Install CI dependencies
        run: yarn install --frozen-lockfile

      # - name: Submodule switch to master/main branch
      #   run: git submodule foreach "git switch main || git switch master || true"

      - name: test
        run: |
          yarn nx format:write --uncommitted
          echo 1
          git submodule foreach 'echo $sha1, echo $(git rev-parse origin/HEAD)'
          echo 2
          git submodule foreach 'git diff $sha1..$(git rev-parse origin/HEAD) --name-only'
          echo 3
          git submodule foreach 'files=$(git diff $sha1..$(git rev-parse origin/HEAD) --name-only | xargs) && echo _${files}_'
          echo 4
          git submodule foreach 'files=$(git diff $sha1..$(git rev-parse origin/HEAD) --name-only | xargs -I {} sh -c "echo $sm_path/{}" | xargs) && cd ../../ && yarn nx format:write --files $files'
          git submodule foreach 'files=$(git diff $sha1..$(git rev-parse origin/HEAD) --name-only | xargs -I {} sh -c "echo $sm_path/{}" | xargs) && if [ $files ]; then echo yarn nx format:write --files $files >> ../../format.sh; fi'
          if [ -f format.sh ];
            cat format.sh
            sh format.sh
            rm format.sh
          fi
