name: Last successful workflow run info

on:
  workflow_call:
    inputs:
      workflowId:
        type: number
        description: the github workflow id
        required: true

jobs:
  workflow_info:
    name: Get the last workflow run info
    runs-on: ubuntu-latest
    outputs:
      head_branch: ${{ steps.lastWorflowInfo.outputs.head_branch }}
      event: ${{ steps.lastWorflowInfo.outputs.event }}
    steps:
      - name: Get last successful workflow runs
        run: "gh api \
          -H \"Accept: application/vnd.github+json\"
          -H \"X-GitHub-Api-Version: 2022-11-28\" \
          \"/repos/${{ github.repository }}/actions/workflows/${{ inputs.workflowId }}/runs?status=success\" \
          | jq -r '.workflow_runs[0]|{head_branch,event}' > temp.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate output
        id: lastWorflowInfo
        run: |
          head_branch=$(jq -r .head_branch < temp.json)
          event=$(jq -r .event < temp.json)
          echo $head_branch
          echo $event
          echo "head_branch=$head_branch" >> $GITHUB_OUTPUT
          echo "event=$event" >> $GITHUB_OUTPUT
