name: Dev(master) release

on:
  push:
    branches:
      - master
    paths:
      - "CHANGELOG.md"

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: dev
      workflowId: master-release.yaml
    secrets: inherit
    name: Deploy AWS - Dev environment
