name: Dev(master) release

on:
  push:
    branches:
      - master

jobs:
  pre-deploy:
    uses: ./.github/workflows/last-successful-workflow-info.yml
    with:
      workflowId: 60653737
    secrets: inherit
    name: Generate last workflow run info output

  deploy-aws:
    needs: pre-deploy
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: dev
      lastSuccessBranch: ${{ needs.pre-deploy.outputs.head_branch }}
      lastSuccessfulEvent: ${{ needs.pre-deploy.outputs.event }}
    secrets: inherit
    name: Deploy AWS - Dev environment
