name: Dev(master) release

on:
  push:
    branches:
      - master

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: dev
      lastSuccessBranch: master
    secrets: inherit
    name: Deploy AWS - Dev environment
