name: Dev(master) release

on:
  push:
    branches:
      - master

jobs:
  deploy-aws:
    strategy:
      matrix:
        env: [sandbox, dev]
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: ${{ matrix.env }}
      workflowId: master-release.yaml
    secrets: inherit
    name: Deploy AWS - Sandbox/Dev environment
