name: Dev(master) release

on:
  push:
    branches:
      - master

jobs:
  deploy-aws:
    needs: pre-deploy
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: dev
      workflowId: 60653737
    secrets: inherit
    name: Deploy AWS - Dev environment
