name: matrix

run-name: operation

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  matrix:
    name: check matrix
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        env_name: [sandbox, dev, staging, prod]
    environment: ${{ matrix.env_name }}
    steps:
      - name: print env_name
        run: echo ${{matrix.env_name}} from inline

      - name: matrix to environment
        run: echo $ENV_NAME from environment
        env:
          ENV_NAME: ${{matrix.env_name}}

      - name: matrix to environment
        run: echo $ENV_NAME from step environment
        env:
          ENV_NAME: ${{matrix.env_name}}

      - name: matrix in repo environment
        run: echo $ENV_NAME from repo environment
        env:
          ENV_NAME: ${{vars.ENV_NAME}}

      - name: do some long time task
        run: |
          attempt_num=0
          max_attempts=3
          success=false
          while [ $success = false ] && [ $attempt_num -lt $max_attempts ]; do
            echo "attempt_num: $attempt_num"

            type bbb

            if [ $? -eq 0 ]; then
              success=true
            else
              attempt_num=$((attempt_num + 1))
              sleep_seconds=$(( $RANDOM % 10 + 1 ))
              echo "sleep_seconds:$sleep_seconds"
              sleep $sleep_seconds
            fi
          done

        env:
          ENV_NAME: ${{matrix.env_name}}
