name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  shell:
    name: pr test
    runs-on: [self-hosted, macos]
    steps:
      - name: env
        run: env
      - name: github event
        run: echo ${{ toJSON(github) }}
