name: Dev(Prod) release

on:
  workflow_dispatch:
    inputs:
      lastSuccessBranch:
        type: string
        description:  last successful branch for nx get the last successful deployment

jobs:
  pre-deploy:
    uses: ./.github/workflows/last-successful-workflow-info.yml
    with:
      workflowId: "60661226"
    secrets: inherit
    name: Generate last workflow run info output

  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: prod
      lastSuccessBranch: release-1.6.x
      lastSuccessfulEvent: workflow_dispatch
      
    secrets: inherit
    name: Deploy AWS - Staging environment
