name: Dev(Prod) release

on: workflow_dispatch

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: prod
      workflowId: prod-release.yaml
    secrets: inherit
    name: Deploy AWS - Staging environment
