name: Dev(Prod) release

on:
  workflow_dispatch:
    inputs:
      lastSuccessBranch:
        type: string
        description:  last successful branch for nx get the last successful deployment

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: prod
      workflowId: 60661226
    secrets: inherit
    name: Deploy AWS - Staging environment
