name: Dev(Prod) release

on:
  workflow_dispatch

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: prod
      workflowId: 60661226
    secrets: inherit
    name: Deploy AWS - Staging environment
