name: Test Pull Request

on:
  pull_request:
    branches:
      - master1

jobs:
  pr:
    name: test pr
    runs-on: ubuntu-latest
    steps:
      - name: context
        run: echo ${{github.ref}}
