name: Test Pull Request

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}

jobs:
  pr:
    name: test pr
    runs-on: ubuntu-latest
    steps:
      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: context
        run: echo ${{github.ref}}
