name: Test self host runner

on: workflow_dispatch

jobs:
  shell:
    name: self host runner
    runs-on: demo
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: check env
        run: env

      - name: ls command
        run: ls /bin/

      - name: check command
        run: |
          jq --version || true
          aws --version || true
          gh --version || true
          node --version || true
          yarn --version || true
          yarnpkg --version || true
