name: Setup aws-tools

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        type: string
        description: the aws-tools version
        required: true

jobs:
  aws-tools:
    name: Setup aws-tools
    runs-on: ubuntu-latest
    steps:
      - name: Apply the aws-tools cache
        uses: actions/cache@v3
        id: cache-aws-tools
        with:
          key: aws-tools-${{inputs.version}}
          path: linux-amd64-aws-tools

      - name: Download aws-tools
        if: steps.cache-aws-tools.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/nnsay/aws-tools/releases/download/v${{inputs.version}}/linux-amd64-aws-tools
          chmod +x linux-amd64-aws-tools
