name: Test shell scripts

on: workflow_dispatch

jobs:
  shell:
    name: test shell
    runs-on: ubuntu-latest
    steps:
      - name: export
        run: |
          export VITE_TAG=1.0.1
          echo "VITE_TAG: $VITE_TAG"
          env
      - name: outout export from above step
        run: echo VITE_TAG $VITE_TAG
      - name: check env
        run: env

