name: Dev(Stagign) release

on:
  push:
    branches:
      - release*

jobs:
  deploy-aws:
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: staging
      lastSuccessBranch: release-1.6.x
      lastSuccessfulEvent: push
    secrets: inherit
    name: Deploy AWS - Staging environment
