name: Dev(Stagign) release

on:
  push:
    branches:
      - release*

jobs:
  pre-deploy:
    uses: ./.github/workflows/last-successful-workflow-info.yml
    with:
      workflowId: 60653738
    secrets: inherit
    name: Generate last workflow run info output
    
  deploy-aws:
    needs: pre-deploy
    uses: ./.github/workflows/deploy-aws.yml
    with:
      envName: staging
      lastSuccessBranch: ${{ needs.pre-deploy.outputs.head_branch }}
      lastSuccessfulEvent: ${{ needs.pre-deploy.outputs.event }}
    secrets: inherit
    name: Deploy AWS - Staging environment
