name: reused workfow caller

run-name: ${{ inputs.env_name }} operation 

on:
  workflow_dispatch:

env:
  JOB_ENV1: p1
  JOB_ENV2: p2

jobs:
  caller:
    uses: ./.github/workflows/call.yaml
    with:
      iparameter: 'test01'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  output:
    runs-on: ubuntu-latest
    needs: caller
    steps:
      - name: Print output
        run: echo "result value is ${{ needs.caller.outputs.result }}"
