name: reused workfow caller

run-name: ${{ inputs.envName }} operation 

on:
  workflow_dispatch:
    inputs:
      envName:
        description: give env name
        required: true
        type: choice
        default: sandbox
        options:
          - sandbox
          - dev

env:
  JOB_ENV1: p1
  JOB_ENV2: p2

jobs:
  caller:
    uses: ./.github/workflows/call.yaml
    with:
      iparameter: 'test01'
      envName: ${{ inputs.envName }}
    # secrets:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    secrets: inherit # same with above
  output:
    runs-on: ubuntu-latest
    needs: caller
    steps:
      - name: Print output
        run: echo "result value is ${{ needs.caller.outputs.result }}"
