name: Test nx shas

on:
  pull_request:
    branches:
      - master

jobs:
  nx-sha:
    name: test nx shas
    runs-on: windows-latest
    steps:
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
