name: Workflow run

on:
  workflow_run:
    workflows: [Dev(master) release]
    types:
      - completed

jobs:
  run:
    name: Workflow run logic
    runs-on: ubuntu-latest
    steps:
      - name: Do more something
        run: echo "Do more something"
